# Generated by Django 4.2 on 2024-01-17 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(blank=True, max_length=100, null=True)),
                ('relacion1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=100, null=True)),
                ('relacion2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Región',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='UsersMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('correoduoc', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('semestre', models.CharField(blank=True, max_length=100, null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fnacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna')),
                ('contacto_emergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contactoemergencia')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.nacionalidad')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfiles')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersmetadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Metadata',
                'verbose_name_plural': 'Users Metadata',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='secciones', to='core.usersmetadata')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.region'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('docentes', models.ManyToManyField(blank=True, related_name='asignaturas', to='core.usersmetadata')),
                ('secciones', models.ManyToManyField(blank=True, related_name='asignaturas', to='core.seccion')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignaturas',
            },
        ),
    ]
