# Generated by Django 4.2 on 2024-01-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='comuna',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='region',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.region'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.sexo'),
        ),
    ]
