# Generated by Django 4.2 on 2024-01-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comuna_region_alter_usersmetadata_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmetadata',
            name='region',
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.region'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sexo'),
        ),
    ]
