# Generated by Django 4.2 on 2024-03-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='secciones',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='alumnos',
        ),
        migrations.AddField(
            model_name='seccion',
            name='asignatura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asignatura'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nombreseccion'),
        ),
    ]
