# Generated by Django 4.2 on 2024-03-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nombreseccion_remove_asignatura_secciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='docentes',
        ),
    ]
