# Generated by Django 4.2 on 2024-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_asignatura_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='usuarios',
            field=models.ManyToManyField(default=None, related_name='secciones', to='core.usersmetadata'),
        ),
        migrations.AddField(
            model_name='usersmetadata',
            name='asignaturas_inscritas',
            field=models.ManyToManyField(blank=True, related_name='alumnos_inscritos', to='core.asignatura'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
