# Generated by Django 4.2 on 2024-03-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seccion_usuarios_usersmetadata_asignaturas_inscritas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='contacto_emergencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactoemergencia'),
        ),
    ]
