# Generated by Django 4.2 on 2024-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usersmetadata_contacto_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='semestre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
