# Generated by Django 4.2 on 2024-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usersmetadata_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
