# Generated by Django 4.2 on 2024-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seccion_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='correoduoc',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
