# Generated by Django 4.2 on 2024-04-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usersmetadata_correoduoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfiles'),
        ),
    ]
