# Generated by Django 4.2 on 2024-04-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usersmetadata_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacionalidad',
            name='iso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='comuna',
            field=models.ForeignKey(blank=True, default=46, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna'),
        ),
    ]
