# Generated by Django 4.2 on 2024-04-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_nacionalidad_iso_alter_usersmetadata_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='comuna',
            field=models.ForeignKey(blank=True, default=61, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='usersmetadata',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, default=48, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nacionalidad'),
        ),
    ]
