# Generated by Django 4.2 on 2024-02-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
        ('alumno', '0002_alter_documento_inasis_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_inasis',
            name='users_metadata',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.usersmetadata'),
        ),
    ]
