# Generated by Django 4.2 on 2024-02-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
        ('coordinador', '0016_pronosticoclima_ultima_actualizacion_api'),
        ('alumno', '0003_alter_documento_inasis_users_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bajada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BajaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bajada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='alumno.bajada')),
                ('estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='core.usersmetadata')),
                ('salida_terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinador.salidaterreno')),
            ],
        ),
    ]
