# Generated by Django 4.2 on 2024-02-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
        ('coordinador', '0016_pronosticoclima_ultima_actualizacion_api'),
        ('alumno', '0004_bajada_bajaestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajaestudiante',
            name='estado',
        ),
        migrations.AlterField(
            model_name='bajada',
            name='descripcion',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bajada',
            name='nombre',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bajaestudiante',
            name='bajada',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='alumno.bajada'),
        ),
        migrations.AlterField(
            model_name='bajaestudiante',
            name='estudiante',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='core.usersmetadata'),
        ),
        migrations.AlterField(
            model_name='bajaestudiante',
            name='salida_terreno',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.salidaterreno'),
        ),
    ]
