# Generated by Django 4.2 on 2024-02-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_bajada_salida_terreno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajaestudiante',
            name='salida_terreno',
        ),
    ]
