# Generated by Django 4.2 on 2024-03-25 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seccion_usuarios'),
        ('alumno', '0009_alter_bajada_salida_terreno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCerMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/documentos_cer_medico/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.estado')),
                ('users_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cer_medico', to='core.usersmetadata')),
            ],
        ),
    ]
