# Generated by Django 4.2 on 2024-01-16 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField()),
                ('numero_cuenta', models.IntegerField()),
                ('semestre', models.CharField()),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)])),
                ('semana', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('actividad', models.CharField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('noches', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('dias_actividad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('lugar_ejecucion', models.CharField(max_length=60)),
                ('asignatura', models.CharField()),
                ('exp_aprendizaje', models.CharField()),
                ('num_alumnos', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
                ('seccion_docente', models.CharField()),
                ('docente_titular', models.CharField()),
                ('docentes_apoyo', models.TextField(max_length=100)),
                ('num_salida', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('asig_comp_terreno', models.CharField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
