# Generated by Django 4.2 on 2024-01-17 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('semestre', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)])),
                ('actividad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('noches', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('dias_actividad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('lugar_ejecucion', models.CharField(max_length=60)),
                ('num_alumnos', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('docentes_apoyo', models.TextField(max_length=100)),
                ('num_salida', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('observaciones', models.TextField()),
                ('asig_comp_terreno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_terreno_asig_comp_terreno', to='core.asignatura')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_terreno_asignatura', to='core.asignatura')),
                ('diasemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinador.diasemana')),
                ('docente_titular', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_terreno_titular', to='core.usersmetadata')),
                ('exp_aprendizaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.expaprendizaje')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinador.situacion')),
            ],
            options={
                'verbose_name': 'Salida Terreno',
                'verbose_name_plural': 'Salidas Terreno',
            },
        ),
    ]
