# Generated by Django 4.2 on 2024-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='actividad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='asig_comp_terreno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='asignatura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='docente_titular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='exp_aprendizaje',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='seccion_docente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='situacion',
            field=models.IntegerField(),
        ),
    ]
