# Generated by Django 4.2 on 2024-01-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_alter_salidaterreno_docentes_apoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaterreno',
            name='diasemana',
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='diasemana',
            field=models.ManyToManyField(blank=True, null=True, to='coordinador.diasemana'),
        ),
    ]
