# Generated by Django 4.2 on 2024-01-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_alter_salidaterreno_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='situacion',
            field=models.CharField(),
        ),
    ]
