# Generated by Django 4.2 on 2024-01-17 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0004_remove_salidaterreno_diasemana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='semana',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
