# Generated by Django 4.2 on 2024-01-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0004_alter_salidaterreno_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='actividad',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='asig_comp_terreno',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='asignatura',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='dias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='dias_actividad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='docente_titular',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='exp_aprendizaje',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='lugar_ejecucion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='noches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='numero_cuenta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='seccion_docente',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.CharField(),
        ),
    ]
