# Generated by Django 4.2 on 2024-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0005_alter_salidaterreno_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
