# Generated by Django 4.2 on 2024-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0006_alter_salidaterreno_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.CharField(),
        ),
    ]
