# Generated by Django 4.2 on 2024-01-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
        ('coordinador', '0006_alter_salidaterreno_diasemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='seccion',
            field=models.ManyToManyField(blank=True, related_name='salidas_terreno', to='core.seccion'),
        ),
    ]
