# Generated by Django 4.2 on 2024-01-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersmetadata_region_comuna_region_and_more'),
        ('coordinador', '0007_salidaterreno_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaterreno',
            name='asig_comp_terreno',
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='asig_comp_terreno',
            field=models.ManyToManyField(blank=True, related_name='salidas_terreno_asig_comp_terreno', to='core.asignatura'),
        ),
    ]
