# Generated by Django 4.2 on 2024-01-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0008_remove_salidaterreno_asig_comp_terreno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaterreno',
            name='dias_actividad',
        ),
    ]
