# Generated by Django 4.2 on 2024-02-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0009_remove_salidaterreno_dias_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='semaforo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.semaforo'),
        ),
    ]
