# Generated by Django 4.2 on 2024-02-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0010_semaforo_salidaterreno_semaforo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='semaforo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.semaforo'),
        ),
    ]
