# Generated by Django 4.2 on 2024-02-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0011_alter_salidaterreno_semaforo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronosticoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('temp_max_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_min_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uv_index', models.IntegerField()),
                ('probabilidad_lluvia', models.IntegerField()),
                ('condiciones', models.CharField(max_length=200)),
                ('icono', models.URLField()),
                ('salida_terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinador.salidaterreno')),
            ],
            options={
                'unique_together': {('salida_terreno', 'fecha')},
            },
        ),
    ]
