# Generated by Django 4.2 on 2024-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0012_pronosticoclima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pronosticoclima',
            options={'verbose_name': 'Pronóstico Clima', 'verbose_name_plural': 'Pronósticos Clima'},
        ),
        migrations.RemoveField(
            model_name='pronosticoclima',
            name='nombre_lugar',
        ),
        migrations.RemoveField(
            model_name='pronosticoclima',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pronosticoclima',
            name='temp_max_c',
        ),
        migrations.RemoveField(
            model_name='pronosticoclima',
            name='temp_min_c',
        ),
        migrations.AddField(
            model_name='pronosticoclima',
            name='temperatura_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pronosticoclima',
            name='temperatura_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pronosticoclima',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pronosticoclima',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='comuna',
            field=models.CharField(blank=True, default='sin informacion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='condiciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='icono',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='probabilidad_lluvia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='region',
            field=models.CharField(blank=True, default='sin informacion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pronosticoclima',
            name='uv_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
