# Generated by Django 4.2 on 2024-02-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0013_alter_pronosticoclima_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pronosticoclima',
            old_name='comuna',
            new_name='pais',
        ),
    ]
