# Generated by Django 4.2 on 2024-02-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0014_rename_comuna_pronosticoclima_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatura_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion_text', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_icono', models.URLField(blank=True, null=True)),
                ('ultima_actualizacion_servidor', models.DateTimeField(auto_now=True)),
                ('ultima_actualizacion_api', models.DateTimeField(blank=True, null=True)),
                ('salida_terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinador.salidaterreno')),
            ],
            options={
                'verbose_name': 'Clima Actual',
                'verbose_name_plural': 'Climas Actuales',
                'unique_together': {('salida_terreno',)},
            },
        ),
    ]
