# Generated by Django 4.2 on 2024-03-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seccion_usuarios'),
        ('coordinador', '0019_asignacionusuarioseccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaterreno',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_terreno_asignatura', to='core.asignatura'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
