# Generated by Django 4.2 on 2024-03-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seccion_usuarios'),
        ('coordinador', '0021_remove_salidaterreno_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaterreno',
            name='asig_comp_terreno',
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='asig_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_terreno_asignatura', to='core.asignatura'),
        ),
    ]
