# Generated by Django 4.2 on 2024-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0022_remove_salidaterreno_asig_comp_terreno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
