# Generated by Django 4.2 on 2024-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0023_alter_salidaterreno_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
            ],
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='documentos',
            field=models.ManyToManyField(blank=True, null=True, to='coordinador.documentosterreno'),
        ),
    ]
