# Generated by Django 4.2 on 2024-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0027_remove_salidaterreno_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosterreno',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
