# Generated by Django 4.2 on 2024-04-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_usersmetadata_comuna_and_more'),
        ('coordinador', '0028_documentosterreno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordinador.actividad'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='asig_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_terreno_asignatura', to='core.asignatura'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='docente_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_terreno_titular', to='core.usersmetadata'),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='exp_aprendizaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordinador.expaprendizaje'),
        ),
    ]
